### ISSUE TITLE
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged

### ISSUE THREAD

**Issue by Henryluoluoluo** [Shengcao-Cao/CMT#11]
When I train using CMT-AT, this error occurs. How to solve it?This error also appeared in AT, but the author has not solved it yet.
**FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged**

**Comment by weiailipeiran** [comment]
> When I train using CMT-AT, this error occurs. How to solve it?This error also appeared in AT, but the author has not solved it yet. **FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged**
hello，did you solve this problem，can you help me？
