### ISSUE TITLE
为什么teacher刚开始的时候准确率最高，之后一路下降？

### ISSUE THREAD

**Issue by OrientSama** [Shengcao-Cao/CMT#12]
使用xview和dota数据集的公共类，从xview迁移到dota，
![image](https://github.com/Shengcao-Cao/CMT/assets/81564896/3cf9159b-3639-46ee-80c1-59e0422f8312)
训练结果是最开始的时候map达到了50，之后越训练越低，最后38左右。
请问这是什么原因？

**Comment by Shengcao-Cao** [comment]
@OrientSama 你好，

在训练过程中我也观察到过类似的现象，似乎在mean teacher相关的方法中是比较普遍的。这有可能是由overfitting造成的。建议调整learning rate以及训练的时长。
