### ISSUE TITLE
Where is the definition of contrastive learning loss? I can't find it.

### ISSUE THREAD

**Issue by suojinhui** [Shengcao-Cao/CMT#13]
Where is the definition of contrastive learning loss? I can't find it.

**Comment by Shengcao-Cao** [comment]
Hello @suojinhui , you may find the contrastive learning loss here: https://github.com/Shengcao-Cao/CMT/blob/029cd21d0d77252d1309f87b83c05d1752055e56/CMT_AT/adapteacher/engine/trainer.py#L784

**Comment by suojinhui** [comment]
Thank you for your reply!
