### ISSUE TITLE
如何得到VOC2007_foggytrain数据集

### ISSUE THREAD

**Issue by Bradly-s** [Shengcao-Cao/CMT#14]
如何使用trans_seg_to_det_multi.py制作VOC2007_foggytrain数据集？

**Comment by Shengcao-Cao** [comment]
Hello @Bradly-s ,

This script seems to be part of the Probabilistic Teacher work's code. Would you mind opening an issue in the original repo? It has been a long time and I cannot really recall how to convert the data exactly. Sorry about that.

Best,
Shengcao
