### ISSUE TITLE
how to eval your model in KITTI 2 Cityspace   or KITTI 

### ISSUE THREAD

**Issue by ouyang11111** [Shengcao-Cao/CMT#5]
thanks for your contribute in corss-domain object detect     I don't know how to eval you provided model in KITTI 2 Cityspace,  the configs you provided may lack of yaml files about clipart or KITTI 
![image](https://github.com/Shengcao-Cao/CMT/assets/90245729/afe906e6-b886-4aca-98e1-b662f9fb896c)

**Comment by Shengcao-Cao** [comment]
Hello @ouyang11111 ,

We only have the model trained for "KITTI -> Cityscapes" which corresponds to this config file for Probablistic Teacher (PT): https://github.com/Shengcao-Cao/CMT/blob/main/CMT_PT/configs/pt/final_k2c.yaml.

Best,
Shengcao
