### ISSUE TITLE
about the vgg16_bn-6c64b313_converted.pth checkpoint

### ISSUE THREAD

**Issue by Hyouka-qitanta** [Shengcao-Cao/CMT#7]
what's the difference between vgg16_bn-6c64b313_converted.pth and vgg16_bn-6c64b313.pth? if they are different how can i get the  vgg16_bn-6c64b313_converted.pth?

**Comment by ASDF1428** [comment]
我想问一下vgg16_bn-6c64b313_converted.pth要怎么获取
