### ISSUE TITLE
question about pre-trained models of vgg16_caffe.pth

### ISSUE THREAD

**Issue by ouyang11111** [Shengcao-Cao/CMT#8]
Hello, due to issues with the pre-trained models, I am unable to reproduce the training of kitti2city at the moment.

In the PyTorch code, the required file is vgg16_caffe.pth, but what you provided is vgg16_bn-6c64b313_converted.pt (which throws an error: KeyError: 'features.0.weight' and cannot be trained). 

Additionally, the download page for vgg16_caffe.pth from the PT paper is no longer available.

I attempted to download vgg16_bn-6c64b313.pth from the official PyTorch website, but it also cannot be trained.

how can I success train a kitti2city, hope for your reply,

 thanks for your contribution in this area.

**Comment by Shengcao-Cao** [comment]
Hello @ouyang11111 ,

Here's my local copy of the file `vgg16_caffe.pth`: https://drive.google.com/file/d/1KEun_uXv5ycKQdeDjLjWU-GaWo0uFLEH/view?usp=sharing

If it still does not work, please directly open an issue in the original PT repo.

Best,
Shengcao

**Comment by ouyang11111** [comment]
> Hello @ouyang11111 ,
> 
> Here's my local copy of the file `vgg16_caffe.pth`: https://drive.google.com/file/d/1KEun_uXv5ycKQdeDjLjWU-GaWo0uFLEH/view?usp=sharing
> 
> If it still does not work, please directly open an issue in the original PT repo.
> 
> Best, Shengcao

thanks for your reply but your model may corrupted. by your up-loading process . could you please re-upload one?  thanks 
the model mistake shows in terminal as follows: 
![image](https://github.com/Shengcao-Cao/CMT/assets/90245729/cbd9310c-e69b-490e-8f4a-bfb1d5da7054)
and the Netron(its function to view the model structure ) shows same mistake as follows:
![image](https://github.com/Shengcao-Cao/CMT/assets/90245729/cf674ba2-b295-40ca-ac6a-0edd533a5c39)

**Comment by ouyang11111** [comment]
could you re-upload your&nbsp;vgg16_caffe.pth, the model you provided&nbsp; may wrong


jianfeiou
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shengcao-Cao/CMT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 凌晨2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Shengcao-Cao/CMT] question about pre-trained models of vgg16_caffe.pth (Issue #8)





 
Hello @ouyang11111 ,
 
Here's my local copy of the file vgg16_caffe.pth: https://drive.google.com/file/d/1KEun_uXv5ycKQdeDjLjWU-GaWo0uFLEH/view?usp=sharing
 
If it still does not work, please directly open an issue in the original PT repo.
 
Best,
 Shengcao

**Comment by Shengcao-Cao** [comment]
Hello @ouyang11111 ,

Sorry for the corrupted file. Please check this new link: https://drive.google.com/file/d/1eEaoecyh6CFlZvVWdUfDVz85lHF8DNaq/view?usp=sharing

Best,
Shengcao
